AppBundle\Entity\Album:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name
            errorPath: name
            message: 'An album with the same name already exists'
    properties:
        name: