# src/AppBundle/Resources/config/doctrine/Album.orm.yml
AppBundle\Entity\Album:

    type: entity
    table: album
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        year:
            type: integer
    oneToMany:
        songs:
            targetEntity: Song
            mappedBy: album
            cascade: [persist]